version: '3.8'

services:
  symptom_classifier:
    build: .
    ports: 
      - "8501:8501"
    volumes:
      - ./dags:/app/dags
  
  airflow:
    image: apache/airflow:2.5.2
    environment:
      - AIRFLOW__WEBSERVER__WEB_SERVER_HOST=0.0.0.0
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////usr/local/airflow/airflow.db
      - AIRFLOW__WEBSERVER__BASE_URL=http://localhost:8080
      - _AIRFLOW_WWW_USER_NAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
    user: "0:0"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./db:/usr/local/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username delakoka --password delakoka --firstname Admin --lastname User --role Admin --email ksyu.kotova.79@gmail.com &&
               airflow scheduler & airflow webserver"
